name: Deploy website via GitHub Pages

on:
  push:
    # TODO: Comment this out for now
    # branches:
    #   - main

defaults:
  run:
    working-directory: website

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build

  js-docs:
    name: Deploy p2panda-js API documentation

    runs-on: ubuntu-latest

    steps:
      - name: Checkout p2panda-js repository
        uses: actions/checkout@v3
        with:
          repository: 'p2panda/p2panda'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.working_directory }}

      - name: Build documentation page
        run: npm run docs
        working-directory: ${{ env.working_directory }}

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.working_directory }}/docs
          destination_dir: lib/p2panda-js
